import React, { Component } from 'react';
import classNames from 'classnames';

import faceicon from 'faceicon.png';

export default class UserList extends Component {
    /*
     * Receives as props:   isSelected
     *                      meta
     *                      handleUserListSelect
     */
    
    constructor(props) {
        super(props);
        this.state = {
        }
    }

    /*
     *  props.meta = {
     *      name:  <user-defined name>,
     *      pts:   <max-points as string>,
     *      army:  <key>,
     *      id:    <auto-generated unique ID>
     *      count: <number of units>
     *  }
     */
    
    render() {
        const classes = classNames({
            "kb-userlist": true,
            "selected": this.props.isSelected
        });
        return (
            <div className={classes}
                 onClick={(e) => this.props.handleUserListSelect(e, this.props.index)} >
                <div className="kb-userlist__name">
                    {this.props.meta.name}
                </div>
                <div className="kb-userlist__img">
                    <img src={faceicon} alt="face-icon" />
                </div>
                <div className="kb-userlist__stat">
                    <p>{this.props.meta.pts}</p>
                    <div>Points</div>
                </div>
                <div className="kb-userlist__stat">
                    <p>{this.props.meta.count}</p>
                    <div>Units</div>
                </div>
            </div>
        );
    }
}

