import React from 'react';
import classNames from 'classnames';

import faceicon from 'faceicon.png';

export default function UserList({meta, index, isSelected, handleUserListSelect, handleListTransitionExit}) {
    /*
     *  props.meta = {
     *      name:  <user-defined name>,
     *      pts:   <max-points as string>,
     *      army:  <key>,
     *      id:    <auto-generated unique ID>
     *      count: <number of units>
     *  }
     */
    const classes = classNames({
        "kb-userlist": true,
        "selected": isSelected
    });
    return (
        <div className={classes} >
            <div className="kb-userlist__name"
                 onClick={(e) => handleUserListSelect(e, index)} >
                {meta.name}
            </div>
            <div className="kb-userlist__img"
                 onClick={(e) => handleListTransitionExit(e, index)} >
                <img src={faceicon} alt="face-icon" />
            </div>
            <div className="kb-userlist__stat">
                <p>{meta.pts}</p>
                <div>Points</div>
            </div>
            <div className="kb-userlist__stat">
                <p>{meta.count}</p>
                <div>Units</div>
            </div>
        </div>
    );
}

